/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tyas
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Bil1 = new javax.swing.JTextField();
        Bil2 = new javax.swing.JTextField();
        Btnkali = new javax.swing.JButton();
        Btnbagi = new javax.swing.JButton();
        Btntambah = new javax.swing.JButton();
        Btnkurang = new javax.swing.JButton();
        Hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Kalkulator Sederhana");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 0, 160, 20);

        jLabel2.setText("Bilangan 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 40, 74, 20);

        jLabel3.setText("Bilangan 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 70, 80, 20);

        jLabel4.setText("Operator");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 110, 80, 20);

        jLabel5.setText("Hasil");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 200, 51, 20);
        getContentPane().add(Bil1);
        Bil1.setBounds(140, 40, 140, 26);
        getContentPane().add(Bil2);
        Bil2.setBounds(140, 70, 140, 26);

        Btnkali.setText("x");
        Btnkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkaliActionPerformed(evt);
            }
        });
        getContentPane().add(Btnkali);
        Btnkali.setBounds(0, 140, 41, 29);

        Btnbagi.setText(":");
        Btnbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbagiActionPerformed(evt);
            }
        });
        getContentPane().add(Btnbagi);
        Btnbagi.setBounds(100, 140, 39, 29);

        Btntambah.setText("+");
        Btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtntambahActionPerformed(evt);
            }
        });
        getContentPane().add(Btntambah);
        Btntambah.setBounds(200, 140, 45, 29);

        Btnkurang.setText("-");
        Btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkurangActionPerformed(evt);
            }
        });
        getContentPane().add(Btnkurang);
        Btnkurang.setBounds(300, 140, 39, 29);
        getContentPane().add(Hasil);
        Hasil.setBounds(140, 220, 110, 60);

        setBounds(0, 0, 422, 356);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkaliActionPerformed
        int bilangan1 = Integer.parseInt(Bil1.getText());
        int bilangan2 = Integer.parseInt(Bil2.getText());
        int hasil = bilangan1*bilangan2;
        Hasil.setText(String.valueOf(hasil));
// TODO add your handling code here:
    
    }//GEN-LAST:event_BtnkaliActionPerformed

    private void BtnbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbagiActionPerformed
        int bilangan1 = Integer.parseInt(Bil1.getText());
        int bilangan2 = Integer.parseInt(Bil2.getText());
        int hasil = bilangan1/bilangan2;
        Hasil.setText(String.valueOf(hasil));
// TODO add your handling code here:
    }//GEN-LAST:event_BtnbagiActionPerformed

    private void BtntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtntambahActionPerformed
        int bilangan1 = Integer.parseInt(Bil1.getText());
        int bilangan2 = Integer.parseInt(Bil2.getText());
        int hasil = bilangan1+bilangan2;
        Hasil.setText(String.valueOf(hasil));
// TODO add your handling code here:
    }//GEN-LAST:event_BtntambahActionPerformed

    private void BtnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkurangActionPerformed
        int bilangan1 = Integer.parseInt(Bil1.getText());
        int bilangan2 = Integer.parseInt(Bil2.getText());
        int hasil = bilangan1-bilangan2;
        Hasil.setText(String.valueOf(hasil));
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnkurangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bil1;
    private javax.swing.JTextField Bil2;
    private javax.swing.JButton Btnbagi;
    private javax.swing.JButton Btnkali;
    private javax.swing.JButton Btnkurang;
    private javax.swing.JButton Btntambah;
    private javax.swing.JTextField Hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
